// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/count.ts";
import * as $3 from "./routes/api/messages.ts";
import * as $4 from "./routes/api/ping.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/messages.tsx";
import * as $$0 from "./islands/MessageList.tsx";
import * as $$1 from "./islands/NewMessage.tsx";
import * as $$2 from "./islands/SocketCounter.tsx";
import * as $$3 from "./islands/SocketPing.tsx";

const manifest = {
	routes: {
		"./routes/_404.tsx": $0,
		"./routes/_app.tsx": $1,
		"./routes/api/count.ts": $2,
		"./routes/api/messages.ts": $3,
		"./routes/api/ping.ts": $4,
		"./routes/index.tsx": $5,
		"./routes/messages.tsx": $6,
	},
	islands: {
		"./islands/MessageList.tsx": $$0,
		"./islands/NewMessage.tsx": $$1,
		"./islands/SocketCounter.tsx": $$2,
		"./islands/SocketPing.tsx": $$3,
	},
	baseUrl: import.meta.url,
};

export default manifest;
